#pragma once

#include <memory>
#include <string>

#include "nav2_core/controller.hpp"
#include "nav2_costmap_2d/costmap_2d_ros.hpp"
#include "rclcpp/rclcpp.hpp"
#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "geometry_msgs/msg/pose_stamped.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include <ackermann_msgs/msg/ackermann_drive_stamped.hpp>
#include "nav2_util/geometry_utils.hpp"
#include "tf2_ros/buffer.h"
#include "nav_msgs/msg/path.hpp"
#include "pluginlib/class_list_macros.hpp"
#include "nav2_util/node_utils.hpp"
#include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
#include <pluginlib/class_loader.hpp>
#include <costmap_converter/costmap_converter_interface.h>

// Own imports
#include "nav2_teb_controller/planner/optimal_planner.hpp"
#include "nav2_teb_controller/planner/planner_interface.hpp"
#include "nav2_teb_controller/homotopy/homotopy_class_planner.hpp"
#include "nav2_teb_controller/homotopy/graph_search_interface.hpp"
#include "nav2_teb_controller/homotopy/visibility_graph_search.hpp"
#include "nav2_teb_controller/core/timed_elastic_band.hpp"
#include "nav2_teb_controller/visualization/teb_visualizer.hpp"
#include "nav2_teb_controller/core/footprint.hpp"

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{

class TEBController : public nav2_core::Controller
{
public:
  TEBController() = default;
  ~TEBController() override = default;

  // nav2_core::Controller interface
  void configure(
    const rclcpp_lifecycle::LifecycleNode::WeakPtr & parent,
    std::string name,
    std::shared_ptr<tf2_ros::Buffer> tf,
    std::shared_ptr<nav2_costmap_2d::Costmap2DROS> costmap_ros) override;

  void activate() override;
  void deactivate() override;
  void cleanup() override;

  void setPlan(const nav_msgs::msg::Path & path) override;

  geometry_msgs::msg::TwistStamped computeVelocityCommands(
    const geometry_msgs::msg::PoseStamped & pose,
    const geometry_msgs::msg::Twist & velocity,
    nav2_core::GoalChecker * goal_checker) override;

  void setSpeedLimit(
    const double & speed_limit,
    const bool & percentage) override;

  void initCostmapConverter();

protected:
  // Node handles
  rclcpp_lifecycle::LifecycleNode::WeakPtr node_;
  rclcpp::Logger logger_{rclcpp::get_logger("TEBController")};
  rclcpp::Clock::SharedPtr clock_;

  // Plugin name assigned by controller server
  std::string plugin_name_;

  // Costmap + TF
  std::shared_ptr<nav2_costmap_2d::Costmap2DROS> costmap_ros_;
  std::shared_ptr<tf2_ros::Buffer> tf_;

  // Parameters
  std::shared_ptr<teb_controller::ParamListener> param_listener_;
  teb_controller::Params params_;

  // Current global plan
  nav_msgs::msg::Path global_plan_;

  // Speed limit override (set by costmap speed limit layer)
  double speed_limit_{1.0};
  bool speed_limit_is_percentage_{true};

  // Costmap converter
  rclcpp::Node::SharedPtr intra_proc_node_{nullptr};
  pluginlib::ClassLoader<costmap_converter::BaseCostmapToPolygons> 
    costmap_converter_loader_{"costmap_converter", "costmap_converter::BaseCostmapToPolygons"};
  std::shared_ptr<costmap_converter::BaseCostmapToPolygons> costmap_converter_;

  // Ackermann subscriber
  rclcpp::Subscription<ackermann_msgs::msg::AckermannDriveStamped>::SharedPtr tricycle_state_sub_;
  ackermann_msgs::msg::AckermannDriveStamped last_ackermann_cmd_;

  // Last cmd 
  geometry_msgs::msg::TwistStamped last_cmd_vel_;

  // ESDF
  ObstacleMap2D esdf_;
  rclcpp::Time last_esdf_update_{0, 0, RCL_ROS_TIME};
  rclcpp::Duration esdf_update_period_{0, 0};

  // Footprint object
  Footprint footprint_;

  // internal objects
  std::unique_ptr<PlannerBase> planner_;
  PlannerInterface<TimedElasticBand>* teb_planner_;
  std::unique_ptr<TEBVisualizer> visualizer_;
};

}  // namespace nav2_teb_controller

PLUGINLIB_EXPORT_CLASS(nav2_teb_controller::TEBController, nav2_core::Controller)
