#pragma once

#include <ackermann_msgs/msg/ackermann_drive.hpp>
#include <costmap_converter_msgs/msg/obstacle_array_msg.hpp>
#include <memory>
#include <nav2_teb_controller/obstacles/esdf.hpp>
#include <nav_msgs/msg/path.hpp>
#include <vector>

#include "nav2_costmap_2d/costmap_2d_ros.hpp"
#include "nav2_teb_controller/core/footprint.hpp"
#include "nav2_teb_controller/core/timed_elastic_band.hpp"
#include "nav2_teb_controller/homotopy/graph_search_interface.hpp"
#include "nav2_teb_controller/homotopy/h_signature.hpp"
#include "nav2_teb_controller/homotopy/teb_candidate.hpp"
#include "nav2_teb_controller/planner/planner_interface.hpp"

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller {

/**
 * @brief HCP Wrapper: Finds N homotopy-distinct TEB trajectories
 *        and returns the best feasible one.
 *
 * Usage:
 *   HomotopyClassPlanner hcp(params, costmap);
 *   hcp.setGraphSearch(std::make_shared<VisibilityGraphSearch>());
 *   hcp.plan(path, twist);
 *   auto& best = hcp.getBestCandidate();
 */
class HomotopyClassPlanner : public PlannerInterface<TimedElasticBand> {
public:
  HomotopyClassPlanner(const teb_controller::Params &params, const Footprint &footprint,
                       nav2_costmap_2d::Costmap2DROS *costmap_ros);

  // ── PlannerBase Interface ──────────────────────────────────────────────
  bool plan(const nav_msgs::msg::Path &global_plan,
            const geometry_msgs::msg::Twist &start_vel) override;
  bool hasDiverged() override;
  void clear() override;

  // ── PlannerInterface<TEB> ─────────────────────────────────────────────
  [[nodiscard]] const TimedElasticBand &getTEB() const override;
  void setFeedback(const ackermann_msgs::msg::AckermannDrive & /*feedback*/) override;
  void updateObstacleContainer(
      costmap_converter_msgs::msg::ObstacleArrayMsg::ConstSharedPtr /*obstacle_array*/) override;
  void setObstacleMap(const ObstacleMap2D *esdf) override;
  void setFixedGoal(bool fix) override;

  // ── HCP-specific ──────────────────────────────────────────────────────

  /** @brief Inject graph search strategy (Visibility/ProAStar) */
  void setGraphSearch(std::shared_ptr<GraphSearchInterface> graph_search);

  /** @brief Inject underlying TEB planner (DiscreteTEB/PolynomialTEB) */
  void setBasePlanner(std::shared_ptr<PlannerInterface<TimedElasticBand>> base_planner);

  /** @brief Get all TEB candidates (for visualization) */
  [[nodiscard]] const std::vector<TebCandidate::Ptr> &getCandidates() const { return candidates_; }

  /** @brief Get best TEB candidate */
  [[nodiscard]] const TebCandidate &getBestCandidate() const;

private:
  /**
   * @brief Step 1: Visibility graph search → GraphSearchResult paths
   */
  bool findHomotopyClasses(const PoseSE2 &start, const PoseSE2 &goal,
                           std::vector<GraphSearchResult> &classes);

  /**
   * @brief Step 2: For each class, optimize a TEB
   */
  void optimizeCandidates(const std::vector<GraphSearchResult> &classes,
                          const geometry_msgs::msg::Twist &start_vel);

  /**
   * @brief Step 3: Select best feasible TEB by cost
   */
  [[nodiscard]] int selectBestCandidate() const;

  /**
   * @brief Update existing candidates (warm-start) or init new ones
   */
  void updateCandidates(const std::vector<GraphSearchResult> &classes);

  /**
   * @brief Prune candidates that have diverged or are too costly
   */
  void pruneCandidates();

  const teb_controller::Params &params_;
  const Footprint &footprint_;
  nav2_costmap_2d::Costmap2DROS *costmap_ros_;

  std::shared_ptr<GraphSearchInterface> graph_search_;
  std::shared_ptr<PlannerInterface<TimedElasticBand>> base_planner_;

  std::vector<TebCandidate::Ptr> candidates_;
  int best_candidate_idx_ = -1;

  costmap_converter_msgs::msg::ObstacleArrayMsg::ConstSharedPtr obstacles_;
};

}  // namespace nav2_teb_controller
