#ifndef EDGE_JERK_H
#define EDGE_JERK_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <geometry_msgs/msg/twist.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
/*********************************************************************
 *
 * Wuhan University of Technology
 * 
 * School of Mechanical and Electrical Engineering
 * Author: Liu Rui
 * 

*********************************************************************/  
/**
 * @class EdgeJerk
 * @brief Edge defining the cost function for limiting the translational and rotational jerk.
 * 
 * The edge depends on seven vertices \f$ \mathbf{s}_i, \mathbf{s}_{i+1}, \mathbf{s}_{i+2}, \mathbf{s}_{i+3}, 
 * \Delta T_i, \Delta T_{i+1}, \Delta T_{i+2} \f$ and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [j, omegadotdot]^T ) \cdot weight \f$. \n
 * \e j is calculated using the difference quotient （thrice） and the position parts of four poses. \n
 * \e omegadotdot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi]. \n 
 * \e weight can be set using setInformation() \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval() \n
 * The dimension of the error / cost vector is 2: the first component represents the translational jerk and
 * the second one the rotational jerk
 * @see TebOptimalPlanner::AddEdgesJerk
 * @remarks Do not forget to call setTebConfig()
*/
class EdgeJerk : public BaseTebMultiEdge<2, double>
{
public:
  
  /**
   * @brief Construct edge
  */
  EdgeJerk()
  {
    this->resize(7);
  }

  /**
   * @brief Actual cost function
  */
  void computeError() override
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    // Get four poses and three deltaT
    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose3 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* pose4 = dynamic_cast<const VertexPose*>(_vertices[3]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[5]);
    const auto* dt3 = dynamic_cast<const VertexTimeDiff*>(_vertices[6]);

    // Using the difference quotient to calculate difference quotient
    const Eigen::Vector2d diff1 = pose2->position() - pose1->position();
    const Eigen::Vector2d diff2 = pose3->position() - pose2->position();
    const Eigen::Vector2d diff3 = pose4->position() - pose3->position();

    // Calculate the distance difference between poses
    double dist1 = diff1.norm();
    double dist2 = diff2.norm();
    double dist3 = diff3.norm();

    // Calculate the angle difference between poses
    const double angle_diff1 = angles::normalize_angle(pose2->theta() - pose1->theta());
    const double angle_diff2 = angles::normalize_angle(pose3->theta() - pose2->theta());
    const double angle_diff3 = angles::normalize_angle(pose4->theta() - pose3->theta());

    if (exact_arc_length) // use exact arc length instead of Euclidean approximation
    {
        if (angle_diff1 != 0)
        {
            const double radius = dist1 / (2 * sin(angle_diff1 / 2));
            dist1 = fabs(angle_diff1 * radius); // actual arg length!
        }
        if (angle_diff2 != 0)
        {
            const double radius = dist2 / (2 * sin(angle_diff2 / 2));
            dist2 = fabs(angle_diff2 * radius); // actual arg length!
        }
        if (angle_diff3 != 0)
        {
            const double radius = dist3 / (2 * sin(angle_diff3 / 2));
            dist3 = fabs(angle_diff3 * radius); // actual arg length!
        }
    }

    // LINEAR
    // Calculate the velocity
    double vel1 = dist1 / dt1->dt();
    double vel2 = dist2 / dt2->dt();
    double vel3 = dist3 / dt3->dt();

    // consider directions
    vel1 *= fast_sigmoid(100 * (diff1.x() * cos(pose1->theta()) + diff1.y() * sin(pose1->theta())));
    vel2 *= fast_sigmoid(100 * (diff2.x() * cos(pose2->theta()) + diff2.y() * sin(pose2->theta())));
    vel3 *= fast_sigmoid(100 * (diff3.x() * cos(pose3->theta()) + diff3.y() * sin(pose3->theta())));

    // Calculate the acceleration
    double acc_lin1 = (vel2 - vel1) * 2 / (dt1->dt() + dt2->dt());
    double acc_lin2 = (vel3 - vel2) * 2 / (dt2->dt() + dt3->dt());

    // Calculate and add the jerk
    const double jerk_lin = (acc_lin2 - acc_lin1) / ((dt1->dt() + dt2->dt()) / 4 + (dt2->dt() + dt3->dt()) / 4);

    _error[0] = penaltyBoundToInterval(jerk_lin, jerk_max_x, penalty_eps);

    // ANGULAR
    // Calculate the omega
    double omega1 = angle_diff1 / dt1->dt();
    double omega2 = angle_diff2 / dt2->dt();
    double omega3 = angle_diff3 / dt3->dt();

    // Calculate the acceleration
    double acc_rot1 = (omega2 - omega1) * 2 / (dt1->dt() + dt2->dt());
    double acc_rot2 = (omega3 - omega2) * 2 / (dt2->dt() + dt3->dt());

    // Calculate and add the jerk
    const double jerk_rot = (acc_rot2 - acc_rot1) / ((dt1->dt() + dt2->dt()) / 4 + (dt2->dt() + dt3->dt()) / 4);

    _error[1] = penaltyBoundToInterval(jerk_rot, jerk_max_theta, penalty_eps);
  }


  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};
    
/**
 * @class EdgeJerkStart
 * @brief Edge difining the cost function for limiting the translational and rotational jerk at the beginning of the trajectory.
 * 
 * The edge depends on five vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \mathbf{s}_{ip2}, \Delta T_i \f$, \Delta T_{i+1} \f$ 
 * an initial acceleration defined by setInitialAcceleration() and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [j, omegadotdot ]^T ) \cdot weight \f$. \n
 * \e j is calculated using the difference quotient (thrice) and the position parts of the poses. \n
 * \e omegadotdot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi].  \n
 * \e weight can be set using setInformation(). \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval(). \n
 * The dimension of the error / cost vector is 2: the first component represents the translational jerk and
 * the second one the rotational jerk.
 * @see TebOptimalPlanner::AddEdgesJerk
 * @see EdgeJerk
 * @see EdgeJerkGoal
 * @remarks Do not forget to call setTebConfig()
 * @remarks Refer to EdgeAccelerationGoal() for defining boundary values at the end of the trajectory!
*/
class EdgeJerkStart : public BaseTebMultiEdge<2, const geometry_msgs::msg::Twist*>
{
public:

  /**
   * @brief Constuct edge.
  */
  EdgeJerkStart()
  {
    _measurement = nullptr;
    this->resize(5);
  }
    
  /**
   * @brief Actual cost function
  */
  void computeError() override
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    // Obtain pose and time difference information from vertices
    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose3 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    // Calculate the distance difference and angle difference between poses
    const Eigen::Vector2d diff1 = pose2->position() - pose1->position();
    const Eigen::Vector2d diff2 = pose3->position() - pose2->position();
    double dist1 = diff1.norm();
    double dist2 = diff2.norm();
    const double angle_diff1 = angles::normalize_angle(pose2->theta() - pose1->theta());
    const double angle_diff2 = angles::normalize_angle(pose3->theta() - pose2->theta());

    if (exact_arc_length) // use exact arc length instead of Euclidean approximation
    {
        if (angle_diff1 != 0)
        {
            const double radius =  dist1/(2*sin(angle_diff1/2));
            dist1 = fabs( angle_diff1 * radius ); // actual arg length!
        }
        if (angle_diff2 != 0)
        {
            const double radius =  dist2/(2*sin(angle_diff2/2));
            dist2 = fabs( angle_diff2 * radius ); // actual arg length!
        }
    }
    
    // LINEAR
    // Calculate the velocity
    const double vel0 = _measurement->linear.x;
    double vel1 = dist1 / dt1->dt();
    double vel2 = dist2 / dt2->dt();

    // consider directions
    vel1 *= fast_sigmoid(100 * (diff1.x() * cos(pose1->theta()) + diff1.y() * sin(pose1->theta())));
    vel2 *= fast_sigmoid(100 * (diff2.x() * cos(pose2->theta()) + diff2.y() * sin(pose2->theta())));

    // Calculate the acceleration
    double acc_lin0 = (vel1 - vel0) / dt1->dt();
    double acc_lin1 = (vel2 - vel1) * 2 / (dt1->dt() + dt2->dt());

    // Calculate and add the jerk
    const double jerk_lin = (acc_lin1 - acc_lin0) / (dt1->dt() / 2 + (dt1->dt() + dt2->dt()) / 4);

    _error[0] = penaltyBoundToInterval(jerk_lin, jerk_max_x, penalty_eps);

    // ANGULAR
    // Calculate the omega
    const double omega0 = _measurement->angular.z;
    double omega1 = angle_diff1 / dt1->dt();
    double omega2 = angle_diff2 / dt2->dt();

    // Calculate the acceleration
    double acc_rot0 = (omega1 - omega0) / dt1->dt();
    double acc_rot1 = (omega2 - omega1) * 2 / (dt1->dt() + dt2->dt());

    // Calculate and add the jerk
    const double jerk_rot = (acc_rot1 - acc_rot0) / (dt1->dt() / 2 + (dt1->dt() + dt2->dt()) / 4);

    _error[1] = penaltyBoundToInterval(jerk_rot, jerk_max_theta, penalty_eps);
  }

  /**
   * @brief Set the initial velocity that is taken into account for calculating the acceleration
   * and use this speed to initialize the initial acceleration for the next step
   * @param vel_start twist message containing the translational and rotational velocity
   */    
  void setInitialVelocity(const geometry_msgs::msg::Twist& vel_start)
  {
    _measurement = &vel_start;
  }
  

  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};
    
/**
 * @class EdgeJerkGoal
 * @brief Edge difining the cost function for limiting the translational and rotational jerk at the end of the trajectory.
 * 
 * The edge depends on five vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \mathbf{s}_{ip2}, \Delta T_i \f$, \Delta T_{i+1} \f$ 
 * an initial acceleration defined by setGoalAcceleration() and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [j, omegadotdot ]^T ) \cdot weight \f$. \n
 * \e j is calculated using the difference quotient (thrice) and the position parts of the poses. \n
 * \e omegadotdot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi].  \n
 * \e weight can be set using setInformation(). \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval(). \n
 * The dimension of the error / cost vector is 2: the first component represents the translational jerk and
 * the second one the rotational jerk.
 * @see TebOptimalPlanner::AddEdgesJerk
 * @see EdgeJerk
 * @see EdgeJerkGoal
 * @remarks Do not forget to call setTebConfig()
 * @remarks Refer to EdgeAccelerationGoal() for defining boundary values at the end of the trajectory!
*/
class EdgeJerkGoal : public BaseTebMultiEdge<2, const geometry_msgs::msg::Twist*>
{
public:

  /**
   * @brief Constuct edge.
  */
  EdgeJerkGoal()
  {
    _measurement = nullptr;
    this->resize(5);
  }
    
  /**
   * @brief Actual cost function
  */
  void computeError() override
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    // Obtain pose and time difference information from vertices
    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose_goal = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    // Calculate the distance difference and angle difference between poses
    const Eigen::Vector2d diff1 = pose2->position() - pose1->position();
    const Eigen::Vector2d diff2 = pose_goal->position() - pose2->position();
    double dist1 = diff1.norm();
    double dist2 = diff2.norm();
    const double angle_diff1 = angles::normalize_angle(pose2->theta() - pose1->theta());
    const double angle_diff2 = angles::normalize_angle(pose_goal->theta() - pose2->theta());

    if (exact_arc_length) // use exact arc length instead of Euclidean approximation
    {
        if (angle_diff1 != 0)
        {
            const double radius =  dist1/(2*sin(angle_diff1/2));
            dist1 = fabs( angle_diff1 * radius ); // actual arg length!
        }
        if (angle_diff2 != 0)
        {
            const double radius =  dist2/(2*sin(angle_diff2/2));
            dist2 = fabs( angle_diff2 * radius ); // actual arg length!
        }
    }
    
    // LINEAR
    // Calculate the velocity
    double vel1 = dist1 / dt1->dt();
    double vel2 = dist2 / dt2->dt();
    const double vel3 = _measurement->linear.x;

    // consider directions
    vel1 *= fast_sigmoid(100 * (diff1.x() * cos(pose1->theta()) + diff1.y() * sin(pose1->theta())));
    vel2 *= fast_sigmoid(100 * (diff2.x() * cos(pose2->theta()) + diff2.y() * sin(pose2->theta())));

    // Calculate the acceleration
    double acc_lin1 = (vel2 - vel1) * 2 / (dt1->dt() + dt2->dt());
    double acc_lin2 = (vel3 - vel2) / dt2->dt();

    // Calculate and add the jerk
    const double jerk_lin = (acc_lin2 - acc_lin1) / ((dt1->dt() + dt2->dt()) / 4 + dt2->dt() / 2);

    _error[0] = penaltyBoundToInterval(jerk_lin, jerk_max_x, penalty_eps);

    // ANGULAR
    // Calculate the omega
    double omega1 = angle_diff1 / dt1->dt();
    double omega2 = angle_diff2 / dt2->dt();
    const double omega3 = _measurement->angular.z;

    // Calculate the acceleration
    double acc_rot1 = (omega2 - omega1) * 2 / (dt1->dt() + dt2->dt());
    double acc_rot2 = (omega3 - omega2) / dt2->dt();

    // Calculate and add the jerk
    const double jerk_rot = (acc_rot2 - acc_rot1) / ((dt1->dt() + dt2->dt()) / 4 + dt2->dt() / 2);

    _error[1] = penaltyBoundToInterval(jerk_rot, jerk_max_theta, penalty_eps);
  }

  /**
   * @brief Set the goal / final velocity that is taken into account for calculating the acceleration
   * and use this speed to initialize the goal / final acceleration for the next step
   * @param vel_start twist message containing the translational and rotational velocity
   */    
  void setGoalVelocity(const geometry_msgs::msg::Twist& vel_start)
  {
    _measurement = &vel_start;
  }
  

  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif