#ifndef EDGE_STEERING_RATE_GOAL_H
#define EDGE_STEERING_RATE_GOAL_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
//! Corresponds to EdgeSteeringRate but with initial steering angle for the successor configuration
class EdgeSteeringRateGoal : public BaseTebMultiEdge<1, double>
{
public:

  /**
   * @brief Construct edge.
   */	      
  EdgeSteeringRateGoal()
  {
    this->resize(3); // Since we derive from a g2o::BaseMultiEdge, set the desired number of vertices
  }

  /**
   * @brief Actual cost function
   */  
  void computeError() override
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;
    const double steering_rate_max = params_->FollowPath.robot.steering_rate_max;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    //ROS_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeSteeringRateGoal()");
    const auto* conf1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* conf2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* dt = dynamic_cast<const VertexTimeDiff*>(_vertices[2]);
    Eigen::Vector2d delta_s = conf2->estimate().position() - conf1->estimate().position();
    double dist = delta_s.norm();
    double angle_diff = angles::normalize_angle( conf2->theta() - conf1->theta() );

    double phi;
    if (std::abs(dist) < 1e-12)
    {
      //ROS_INFO("Goal phi is zero!");
        phi = 0;
    }
    else
    {
        if (exact_arc_length)
            phi = std::atan(wheelbase / dist * 2.0*std::sin(angle_diff/2.0));
        else
            phi = std::atan(wheelbase / dist * angle_diff);
        // if we compute the sign of dist1 using the following method, the optimizer get's stuck (possibly due to non-smoothness and atan).
        // In case if we apply the sign to the angle directly, it seems to work:
        phi *= fast_sigmoid( 100.0 * (delta_s.x()*cos(conf1->theta()) + delta_s.y()*sin(conf1->theta())) ); // consider direction
    }
    _error[0] = penaltyBoundToInterval(angles::normalize_angle(_measurement - phi) / dt->dt(), steering_rate_max, penalty_eps);
    //ROS_ASSERT_MSG(std::isfinite(_error[0]), "EdgeSteeringRateGoal::computeError() _error[0]\n",_error[0]);
  }

  void setGoalSteeringAngle(double steering_angle)
  {
      _measurement = steering_angle;
  }


  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif