#ifndef EDGE_STEERING_RATE_H
#define EDGE_STEERING_RATE_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
/**
 * @class EdgeSteeringRate
 * @brief Edge defining the cost function for limiting the steering rate w.r.t. the current wheelbase parameter
 *
 * The edge depends on four vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \mathbf{s}_{ip2} \Delta T_i \f$ .
 * @remarks This edge requires the TebConfig::Robot::whelbase parameter to be set.
 * @remarks Do not forget to call setTebConfig()
 */ 
class EdgeSteeringRate : public BaseTebMultiEdge<1, double>
{
public:

  /**
   * @brief Construct edge.
   */	      
  EdgeSteeringRate()
  {
    this->resize(5); // Since we derive from a g2o::BaseMultiEdge, set the desired number of vertices
  }

  /**
   * @brief Actual cost function
   */  
  void computeError() override
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;
    const double steering_rate_max = params_->FollowPath.robot.steering_rate_max;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* conf1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* conf2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* conf3 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    Eigen::Vector2d delta_s1 = conf2->estimate().position() - conf1->estimate().position();
    Eigen::Vector2d delta_s2 = conf3->estimate().position() - conf2->estimate().position();
    double dist1 = delta_s1.norm();
    double dist2 = delta_s2.norm();
    double angle_diff1 = angles::normalize_angle( conf2->theta() - conf1->theta() );
    double angle_diff2 = angles::normalize_angle( conf3->theta() - conf2->theta() );

    if (dist1 < 1e-12 || dist2 < 1e-12)
    {
        _error[0] = 0.0;
        return;
    }

    const double sign1 = (delta_s1.dot(Eigen::Vector2d(std::cos(conf1->theta()), std::sin(conf1->theta()))) >= 0.0) ? 1.0 : -1.0;
    const double sign2 = (delta_s2.dot(Eigen::Vector2d(std::cos(conf2->theta()), std::sin(conf2->theta()))) >= 0.0) ? 1.0 : -1.0;

    double phi1 = exact_arc_length
        ? std::atan((wheelbase / dist1) * 2.0 * std::sin(angle_diff1 / 2.0))
        : std::atan((wheelbase / dist1) * angle_diff1);
    phi1 *= sign1;

    double phi2 = exact_arc_length
        ? std::atan((wheelbase / dist2) * 2.0 * std::sin(angle_diff2 / 2.0))
        : std::atan((wheelbase / dist2) * angle_diff2);
    phi2 *= sign2;

    const double avg_dt = 0.5 * (dt1->dt() + dt2->dt());
    const double steer_rate = (avg_dt > 1e-12) ? (phi2 - phi1) / avg_dt : 0.0;

    _error[0] = penaltyBoundToInterval(steer_rate, steering_rate_max, penalty_eps);
  }


  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif