#ifndef EDGE_ESDF_OBSTACLE_H_
#define EDGE_ESDF_OBSTACLE_H_

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/core/footprint.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{
/// Dynamic-dimension ESDF obstacle edge.
/// Error dimension = footprint.circles().size() + 1 (set via resize()).
///
/// Error layout:
///   [0 .. N-1] → one component per footprint circle (obstacle penalty)
///   [N]        → inflation penalty at robot center
class EdgeESDFObstacle : public BaseTebUnaryEdge<-1, Eigen::VectorXd, VertexPose>
{
public:
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW

  /// Must be called before addEdge() — sets error dimension.
  void resize(int n_circles) {
    _dimension = n_circles + 1;   // circles + 1 inflation component
    _error.resize(_dimension);
    _error.setZero();
  }

  void computeError() override
  {
		const double min_dist = params_->FollowPath.obstacles.min_obstacle_dist;
    const double inflation_dist = params_->FollowPath.obstacles.inflation_dist;
    const double exp_scale = params_->FollowPath.obstacles.cost_exponent;
    const double epsilon = params_->FollowPath.optimizer.penalty_epsilon;

    const VertexPose* vp = static_cast<const VertexPose*>(this->_vertices[0]);

    const double px = vp->x();
    const double py = vp->y();
    const double ct = std::cos(vp->theta());
    const double st = std::sin(vp->theta());

    // ── Per-circle obstacle penalty ─────────────────────────────────────────
    const auto& circles = footprint_->circles();
    for (int i = 0; i < static_cast<int>(circles.size()); ++i) {
      const auto& c   = circles[i];
      const double wx = px + ct * c.offset.x() - st * c.offset.y();
      const double wy = py + st * c.offset.x() + ct * c.offset.y();

      const double dist = esdf_->query(wx, wy).distance;
      // if (dist < 1e-3) { _error.fill(1e6); return; }
      // if (dist <= c.radius)
      //   _error[i] =  1.0 + std::expm1(exp_scale * ((min_dist + c.radius) - dist)); 
      // else
      _error[i] =  penaltyBoundFromBelow(dist, min_dist + c.radius , epsilon);
    }

    // ── Inflation penalty at robot center ────────────────────────────────────
    _error[_dimension - 1] = penaltyBoundFromBelow(esdf_->query(px, py).distance, inflation_dist, 0.0);
  }

  void setObstacle(const ObstacleMap2D& esdf) { esdf_ = &esdf; }
  void setFootprint(const Footprint& fp) { footprint_ = &fp;   }

private:
  const ObstacleMap2D* esdf_{nullptr};
  const Footprint* footprint_{nullptr};
};

} // end namespace

#endif
