#ifndef EDGE_SNAP_H
#define EDGE_SNAP_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
/**
 * @class EdgeSnap
 * @brief Edge defining the cost function for limiting translational and rotational snap (jounce).
 *
 * This edge implements a G4-continuity constraint for maximum smoothness.
 * It depends on five consecutive vertices s_i, ..., s_i+4 and four time diffs.
 * It minimizes: penalty( [snap_lin, snap_rot]^T )
 * Snap is calculated as the difference quotient of the jerks.
 * This is a computationally expensive edge and should be used with caution.
 * The error dimension is 2 (linear and rotational snap).
 */
class EdgeSnap : public BaseTebMultiEdge<2, double>
{
public:
  EdgeSnap()
  {
    this->resize(9); // 5 Poses, 4 TimeDiffs
  }

  // Hilfsfunktion für das Angle Unwrapping, um Sprünge bei -PI/PI zu vermeiden.
  double unwrap_angle(double angle, double reference_angle)
  {
      double diff = angle - reference_angle;
      diff = angles::normalize_angle(diff);
      return reference_angle + diff;
  }

  void computeError()
  {
    // read params
    const double snap_max_x = params_->FollowPath.robot.snap_max_x;
    const double snap_max_theta = params_->FollowPath.robot.snap_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;

    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeSnap()");
    // Cast all 9 vertices
    const VertexPose* pose1 = static_cast<const VertexPose*>(_vertices[0]);
    const VertexPose* pose2 = static_cast<const VertexPose*>(_vertices[1]);
    const VertexPose* pose3 = static_cast<const VertexPose*>(_vertices[2]);
    const VertexPose* pose4 = static_cast<const VertexPose*>(_vertices[3]);
    const VertexPose* pose5 = static_cast<const VertexPose*>(_vertices[4]);

    const VertexTimeDiff* dt1 = static_cast<const VertexTimeDiff*>(_vertices[5]);
    const VertexTimeDiff* dt2 = static_cast<const VertexTimeDiff*>(_vertices[6]);
    const VertexTimeDiff* dt3 = static_cast<const VertexTimeDiff*>(_vertices[7]);
    const VertexTimeDiff* dt4 = static_cast<const VertexTimeDiff*>(_vertices[8]);

    // ==================== LINEAR PART ====================

    // === VELOCITIES (v1, v2, v3, v4) ===
    const Eigen::Vector2d diff1 = pose2->position() - pose1->position();
    const Eigen::Vector2d diff2 = pose3->position() - pose2->position();
    const Eigen::Vector2d diff3 = pose4->position() - pose3->position();
    const Eigen::Vector2d diff4 = pose5->position() - pose4->position();

    double vel1 = diff1.norm() / dt1->dt();
    double vel2 = diff2.norm() / dt2->dt();
    double vel3 = diff3.norm() / dt3->dt();
    double vel4 = diff4.norm() / dt4->dt();

    vel1 *= fast_sigmoid(100 * (diff1.x() * cos(pose1->theta()) + diff1.y() * sin(pose1->theta())));
    vel2 *= fast_sigmoid(100 * (diff2.x() * cos(pose2->theta()) + diff2.y() * sin(pose2->theta())));
    vel3 *= fast_sigmoid(100 * (diff3.x() * cos(pose3->theta()) + diff3.y() * sin(pose3->theta())));
    vel4 *= fast_sigmoid(100 * (diff4.x() * cos(pose4->theta()) + diff4.y() * sin(pose4->theta())));

    // === ACCELERATIONS (a1, a2, a3) ===
    const double acc1 = (vel2 - vel1) * 2 / (dt1->dt() + dt2->dt());
    const double acc2 = (vel3 - vel2) * 2 / (dt2->dt() + dt3->dt());
    const double acc3 = (vel4 - vel3) * 2 / (dt3->dt() + dt4->dt());

    // === JERKS (j1, j2) ===
    const double jerk1 = (acc2 - acc1) * 2 / (dt1->dt() + dt2->dt() + dt3->dt());
    const double jerk2 = (acc3 - acc2) * 2 / (dt2->dt() + dt3->dt() + dt4->dt());

    // === SNAP (s1) ===
    const double snap_lin = (jerk2 - jerk1) * 2 / (dt1->dt() + dt2->dt() + dt3->dt() + dt4->dt());
    _error[0] = penaltyBoundToInterval(snap_lin, snap_max_x, penalty_eps);


    // ==================== ROTATIONAL PART ====================

    // === ANGULAR VELOCITIES (om1, om2, om3, om4) ===
    std::vector<double> theta(5);
    theta[0] = pose1->theta();
    theta[1] = unwrap_angle(pose2->theta(), theta[0]);
    theta[2] = unwrap_angle(pose3->theta(), theta[1]);
    theta[3] = unwrap_angle(pose4->theta(), theta[2]);
    theta[4] = unwrap_angle(pose5->theta(), theta[3]);

    const double omega1 = (theta[1] - theta[0]) / dt1->dt();
    const double omega2 = (theta[2] - theta[1]) / dt2->dt();
    const double omega3 = (theta[3] - theta[2]) / dt3->dt();
    const double omega4 = (theta[4] - theta[3]) / dt4->dt();

    // === ANGULAR ACCELERATIONS (alpha1, alpha2, alpha3) ===
    const double acc_rot1 = (omega2 - omega1) * 2 / (dt1->dt() + dt2->dt());
    const double acc_rot2 = (omega3 - omega2) * 2 / (dt2->dt() + dt3->dt());
    const double acc_rot3 = (omega4 - omega3) * 2 / (dt3->dt() + dt4->dt());

    // === ROTATIONAL JERKS (j_rot1, j_rot2) ===
    const double jerk_rot1 = (acc_rot2 - acc_rot1) * 2 / (dt1->dt() + dt2->dt() + dt3->dt());
    const double jerk_rot2 = (acc_rot3 - acc_rot2) * 2 / (dt2->dt() + dt3->dt() + dt4->dt());

    // === ROTATIONAL SNAP (s_rot1) ===
    const double snap_rot = (jerk_rot2 - jerk_rot1) * 2 / (dt1->dt() + dt2->dt() + dt3->dt() + dt4->dt());
    _error[1] = penaltyBoundToInterval(snap_rot, snap_max_theta, penalty_eps);

    // TEB_ASSERT_MSG(std::isfinite(_error[0]) && std::isfinite(_error[1]), "EdgeSnap::computeError() produced nan values.");
  }
};

} // end namespace

#endif