#ifndef EDGE_COSTMAP_OBSTACLE_H_
#define EDGE_COSTMAP_OBSTACLE_H_

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include "nav2_costmap_2d/costmap_2d_ros.hpp"
#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{
struct Obstacle {
  std::vector<Eigen::Vector2d> polygon;
  double radius{};  // 0 für Punkt-Obstacles
};

class EdgeCostmapObstacle : public BaseTebUnaryEdge<2, std::nullptr_t, VertexPose>
{
public:
  void computeError() override
  {
    const auto* vp = dynamic_cast<const VertexPose*>(_vertices[0]);
    const double min_dist = params_->FollowPath.obstacles.min_obstacle_dist;
	const double inflation_dist = params_->FollowPath.obstacles.inflation_dist;
    const double epsilon  = params_->FollowPath.optimizer.penalty_epsilon;
	const double cost_exponent = params_->FollowPath.obstacles.cost_exponent;

    // Footprint transformieren
    std::vector<geometry_msgs::msg::Point> footprint;
    nav2_costmap_2d::transformFootprint(
      vp->x(), vp->y(), vp->theta(),
      footprint_, footprint);

	// Footprint als Eigen-Polygon konvertieren (einmalig, nicht pro Obstacle)
	auto toEigenPolygon = [](const std::vector<geometry_msgs::msg::Point>& fp)
	{
		std::vector<Eigen::Vector2d> result;
		result.reserve(fp.size());
		for (const auto& p : fp)
			result.emplace_back(p.x, p.y);
		return result;
	};

	const auto fp_eigen = toEigenPolygon(footprint);

	double dist = 0.0;
	if (obstacle_.polygon.size() == 1) // Punkt + Radius
	{
		dist = distancePointToFootprint(obstacle_.polygon[0], footprint);
		dist = dist - obstacle_.radius;
	}
	else if (obstacle_.polygon.size() == 2) // Linie
	{
		// Footprint-Punkte gegen Segment (Linie hat keine Fläche → SAT nicht nötig)
		dist = std::numeric_limits<double>::max();
		const auto& A = obstacle_.polygon[0];
		const auto& B = obstacle_.polygon[1];
		for (const auto& fp_pt : fp_eigen)
			dist = std::min(dist, distancePointToSegment(fp_pt, A, B));
		dist = dist - obstacle_.radius;
	}
	else if (obstacle_.polygon.size() > 2) // Polygon → SAT
	{
		// SAT gibt signed distance: positiv=frei, negativ=inside
		dist = polygonToPolygonDistance(fp_eigen, obstacle_.polygon);
		// Obstacle-Radius berücksichtigen (falls vorhanden)
		dist = dist - obstacle_.radius;
	}


	/*
	double dist = 0.0;
	if (obstacle_.polygon.size() == 1) // point, consider radius
	{
		dist = distancePointToFootprint(obstacle_.polygon[0], footprint);
		// dist = std::max(0.0, dist - obstacle_.radius);
		dist = dist - obstacle_.radius;
	}
	else if (obstacle_.polygon.size() == 2) // line,
	{
		dist = std::numeric_limits<double>::max();
		const auto& A = obstacle_.polygon[0];
		const auto& B = obstacle_.polygon[1];
		for (const auto& fp : footprint)
		{
			const Eigen::Vector2d p(fp.x, fp.y);
			dist = std::min(dist, distancePointToSegment(p, A, B));
		}
		// dist = std::max(0.0, dist - obstacle_.radius);
		dist = dist - obstacle_.radius;
	}
	else if (obstacle_.polygon.size() > 2) // polygon
	{
		dist = std::numeric_limits<double>::max();
		bool any_inside = false;
		for (const auto& fp : footprint)
		{
			const Eigen::Vector2d p(fp.x, fp.y);
			if (pointInPolygon(p, obstacle_.polygon))
			{
			any_inside = true;
			// Tiefe = minimale Distanz zur nächsten Kante, negativ
			double edge_dist = std::numeric_limits<double>::max();
			const size_t n = obstacle_.polygon.size();
			for (size_t i = 0, j = n - 1; i < n; j = i++)
				edge_dist = std::min(edge_dist,
				distancePointToSegment(p, obstacle_.polygon[j], obstacle_.polygon[i]));
			dist = std::min(dist, -edge_dist);  // negativ → inside
			}
			else
			{
			dist = std::min(dist, distancePointToPolygon(p, obstacle_.polygon));
			}
		}
		if (any_inside && dist > 0.0) dist = 0.0;  // safety clamp
	}    
	*/
    // Glatte Penalty: 0 wenn dist > min_dist, steigt sonst
    _error[0] = penaltyBoundFromBelow(dist, min_dist, epsilon);
	if (cost_exponent != 1.0 && _error[0] > 0.0)
  		_error[0] = min_dist * std::pow(_error[0] / min_dist, cost_exponent);

	// Additional linear inflation cost
    _error[1] = penaltyBoundFromBelow(dist, inflation_dist, 0.0);
  }

  void setObstacle(const Obstacle& obs)	{ obstacle_ = obs; }
  void setFootprint(const std::vector<geometry_msgs::msg::Point>& fp) { footprint_ = fp; }

private:
	double distancePointToPolygon(
		const Eigen::Vector2d& p,
		const std::vector<Eigen::Vector2d>& poly)
	{
		if (pointInPolygon(p, poly)) return 0.0;  // Punkt inside → Kollision
		double min_dist = std::numeric_limits<double>::max();
		const size_t n = poly.size();
		for (size_t i = 0, j = n - 1; i < n; j = i++)
			min_dist = std::min(min_dist, distancePointToSegment(p, poly[j], poly[i]));
		return min_dist;
	}

	static double distancePointToSegment(
		const Eigen::Vector2d& p,
		const Eigen::Vector2d& a,
		const Eigen::Vector2d& b)
	{
		const Eigen::Vector2d ab = b - a;
		const double len2 = ab.squaredNorm();
		if (len2 < 1e-10) return (p - a).norm();  // degeneriertes Segment
		const double t = std::clamp((p - a).dot(ab) / len2, 0.0, 1.0);
		return (p - (a + t * ab)).norm();
	}

	double distancePointToFootprint(
		const Eigen::Vector2d& point,
		const std::vector<geometry_msgs::msg::Point>& polygon)
	{
		if (polygon.empty()) return std::numeric_limits<double>::max();

		// Punkt im Polygon → Distanz = 0 (Kollision)
		if (pointInPolygon(point.x(), point.y(), polygon)) return 0.0;

		// Sonst: Minimale Distanz zu allen Kanten
		double min_dist = std::numeric_limits<double>::max();
		const int n = static_cast<int>(polygon.size());
		for (int i = 0, j = n - 1; i < n; j = i++) {
			Eigen::Vector2d a(polygon[j].x, polygon[j].y);
			Eigen::Vector2d b(polygon[i].x, polygon[i].y);
			Eigen::Vector2d ab = b - a;
			double t = std::clamp((point - a).dot(ab) / ab.squaredNorm(), 0.0, 1.0);
			min_dist = std::min(min_dist, (point - (a + t * ab)).norm());
		}
		return min_dist;
	}

	static bool pointInPolygon(
		double px, double py,const std::vector<geometry_msgs::msg::Point>& polygon)
	{
		bool inside = false;
		const int n = static_cast<int>(polygon.size());
		for (int i = 0, j = n - 1; i < n; j = i++) {
			const double xi = polygon[i].x, yi = polygon[i].y;
			const double xj = polygon[j].x, yj = polygon[j].y;
			if (((yi > py) != (yj > py)) &&
					(px < (xj - xi) * (py - yi) / (yj - yi) + xi))
				inside = !inside;
		}
		return inside;
	}

	static bool pointInPolygon(
		const Eigen::Vector2d& p,
		const std::vector<Eigen::Vector2d>& poly)
	{
		bool inside = false;
		const size_t n = poly.size();
		for (size_t i = 0, j = n - 1; i < n; j = i++)
		{
			const auto& pi = poly[i];
			const auto& pj = poly[j];
			if (((pi.y() > p.y()) != (pj.y() > p.y())) &&
					(p.x() < (pj.x() - pi.x()) * (p.y() - pi.y()) / (pj.y() - pi.y()) + pi.x()))
				inside = !inside;
		}
		return inside;
	}

	static double polygonToPolygonDistance(
	const std::vector<Eigen::Vector2d>& poly_a,  // Footprint
	const std::vector<Eigen::Vector2d>& poly_b)  // Obstacle
	{
	double min_overlap = std::numeric_limits<double>::max();  // kleinste Überlappung (für signed dist)
	double max_gap     = -std::numeric_limits<double>::max(); // größte Lücke (für separation dist)
	bool separated = false;

	// Teste alle Kanten-Normalen beider Polygone als Trennachsen
	for (int poly = 0; poly < 2; ++poly)
	{
		const auto& P = (poly == 0) ? poly_a : poly_b;
		const size_t n = P.size();

		for (size_t i = 0, j = n - 1; i < n; j = i++)
		{
		// Kanten-Normale (nach außen zeigend)
		const Eigen::Vector2d edge  = P[i] - P[j];
		const Eigen::Vector2d axis  = Eigen::Vector2d(-edge.y(), edge.x()).normalized();

		// Projiziere poly_a auf Achse
		double minA =  std::numeric_limits<double>::max();
		double maxA = -std::numeric_limits<double>::max();
		for (const auto& p : poly_a) {
			const double proj = axis.dot(p);
			minA = std::min(minA, proj);
			maxA = std::max(maxA, proj);
		}

		// Projiziere poly_b auf Achse
		double minB =  std::numeric_limits<double>::max();
		double maxB = -std::numeric_limits<double>::max();
		for (const auto& p : poly_b) {
			const double proj = axis.dot(p);
			minB = std::min(minB, proj);
			maxB = std::max(maxB, proj);
		}

		// Lücke auf dieser Achse (positiv = getrennt, negativ = Überlappung)
		const double gap = std::max(minA - maxB, minB - maxA);

		if (gap > 0.0)
		{
			// Trennachse gefunden → Polygone überlappen nicht
			separated = true;
			max_gap = std::max(max_gap, gap);  // größte Lücke = tatsächlicher Abstand
		}
		else
		{
			// Überlappung auf dieser Achse
			min_overlap = std::min(min_overlap, -gap);  // kleinste Überlappung für Eindringtiefe
		}
		}
	}

	if (separated)
		return max_gap;   // positiv: Abstand zwischen Polygonen
	else
		return -min_overlap;  // negativ: Eindringtiefe
	}


  Obstacle obstacle_;
  std::vector<geometry_msgs::msg::Point> footprint_;
};

/*
class EdgeCostmapObstacle : public BaseTebUnaryEdge<1, nullptr_t, VertexPose>
{
public:
	EdgeCostmapObstacle() 
	{
	}

	void computeError() override
	{
		const double min_dist = 0.1; //params_->FollowPath.obstacles.min_obstacle_dist;
		const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
		auto* costmap = costmap_ros_->getCostmap();
		const VertexPose* vp = static_cast<const VertexPose*>(_vertices[0]);

		// Footprint-Zellen scannen → minimale Distanz zum nächsten Obstacle
		std::vector<geometry_msgs::msg::Point> footprint;
		nav2_costmap_2d::transformFootprint(
			vp->x(), vp->y(), vp->theta(),
			costmap_ros_->getRobotFootprint(), footprint);

		// Bounding Box
		double min_x = footprint[0].x, max_x = footprint[0].x;
		double min_y = footprint[0].y, max_y = footprint[0].y;
		for (const auto& pt : footprint) {
			min_x = std::min(min_x, pt.x); max_x = std::max(max_x, pt.x);
			min_y = std::min(min_y, pt.y); max_y = std::max(max_y, pt.y);
		}

		// Suchradius außerhalb des Footprints (bis min_dist)
		const double r = min_dist;
		min_x -= r; min_y -= r; max_x += r; max_y += r;

		int mx0, my0, mx1, my1;
		costmap->worldToMapEnforceBounds(min_x, min_y, mx0, my0);
		costmap->worldToMapEnforceBounds(max_x, max_y, mx1, my1);

		double min_dist_found = std::numeric_limits<double>::max();

		for (int mx = std::max(0, mx0); mx <= std::min(mx1, (int)costmap->getSizeInCellsX() - 1); ++mx) {
  		for (int my = std::max(0, my0); my <= std::min(my1, (int)costmap->getSizeInCellsY() - 1); ++my) {
				unsigned char cell_cost = costmap->getCost(static_cast<unsigned int>(mx), static_cast<unsigned int>(my));
				if (cell_cost < nav2_costmap_2d::LETHAL_OBSTACLE)
					continue;  // nur echte Obstacles

				double wx, wy;
				costmap->mapToWorld(mx, my, wx, wy);

				// Distanz zur nächsten Footprint-Kontur
				double dist = distanceToFootprint(wx, wy, footprint);
				min_dist_found = std::min(min_dist_found, dist);
			}
		}

		// Penalty: 0 wenn weit genug weg, steigt wenn zu nah
		_error[0] = penaltyBoundFromBelow(min_dist_found, min_dist, penalty_eps);
	}

	void setCostmap(nav2_costmap_2d::Costmap2DROS* costmap_ros)
	{
		costmap_ros_ = costmap_ros;
	}
protected:
	double distanceToFootprint(double px, double py,
		const std::vector<geometry_msgs::msg::Point>& polygon)
	{
		double min_dist = std::numeric_limits<double>::max();
		const int n = static_cast<int>(polygon.size());
		for (int i = 0, j = n - 1; i < n; j = i++) {
			// Distanz Punkt → Segment
			const Eigen::Vector2d a(polygon[j].x, polygon[j].y);
			const Eigen::Vector2d b(polygon[i].x, polygon[i].y);
			const Eigen::Vector2d p(px, py);
			const Eigen::Vector2d ab = b - a;
			const double t = std::clamp((p - a).dot(ab) / ab.squaredNorm(), 0.0, 1.0);
			min_dist = std::min(min_dist, (p - (a + t * ab)).norm());
		}
		return min_dist;
	}

	nav2_costmap_2d::Costmap2DROS* costmap_ros_ = nullptr;
	double min_obstacle_cost_ = nav2_costmap_2d::INSCRIBED_INFLATED_OBSTACLE; // default 253
public: 
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};
*/
} // end namespace

#endif
