#ifndef EDGE_STEERING_ANGLE_GOAL_H
#define EDGE_STEERING_ANGLE_GOAL_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{
/**
 * @class EdgeSteeringAngleGoal
 * @brief Edge defining the cost function for forcing the steering angle at the goal to be zero.
 *
 * This edge is intended for car-like or tricycle robots.
 * It penalizes the path curvature at the very end of the trajectory.
 * The edge depends on the last three vertices of the trajectory:
 * s_n-2, s_n-1, s_n (goal).
 * It minimizes: penalty( steering_angle )
 * The steering_angle is calculated from the path curvature, which in turn is
 * derived from the geometry of the three poses.
 * The error dimension is 1.
 */
class EdgeSteeringAngleGoal : public BaseTebMultiEdge<1, double>
{
public:
  EdgeSteeringAngleGoal()
  {
    // This edge now connects 5 vertices (the last 5 poses)
    this->resize(5);
  }

  void computeError() override
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;

    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeSteeringAngleGoal()");
    const auto* pose_n_minus_4 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose_n_minus_3 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose_n_minus_2 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* pose_n_minus_1 = dynamic_cast<const VertexPose*>(_vertices[3]);
    const auto* pose_n = dynamic_cast<const VertexPose*>(_vertices[4]);

    // STEP 1: Perform a least-squares fit to find the best-fit circle for the last 5 points.
    // The equation of a circle is (x-xc)^2 + (y-yc)^2 = R^2.
    // This can be rewritten as 2*x*xc + 2*y*yc + (R^2-xc^2-yc^2) = x^2+y^2.
    // This is a linear system of the form A*p = B, where p = [2*xc, 2*yc, R^2-xc^2-yc^2]^T.

    Eigen::Matrix<double, 5, 3> A;
    Eigen::Matrix<double, 5, 1> B;

    const Eigen::Vector2d p1 = pose_n_minus_4->position();
    const Eigen::Vector2d p2 = pose_n_minus_3->position();
    const Eigen::Vector2d p3 = pose_n_minus_2->position();
    const Eigen::Vector2d p4 = pose_n_minus_1->position();
    const Eigen::Vector2d p5 = pose_n->position();

    A << p1.x(), p1.y(), 1,
         p2.x(), p2.y(), 1,
         p3.x(), p3.y(), 1,
         p4.x(), p4.y(), 1,
         p5.x(), p5.y(), 1;

    B << p1.x()*p1.x() + p1.y()*p1.y(),
         p2.x()*p2.x() + p2.y()*p2.y(),
         p3.x()*p3.x() + p3.y()*p3.y(),
         p4.x()*p4.x() + p4.y()*p4.y(),
         p5.x()*p5.x() + p5.y()*p5.y();

    // Solve the overdetermined system using a robust QR decomposition
    Eigen::Vector3d p = A.colPivHouseholderQr().solve(B);

    // STEP 2: Extract the circle radius from the solution vector p.
    const double xc = p[0] / 2.0;
    const double yc = p[1] / 2.0;
    const double R_squared = p[2] + xc*xc + yc*yc;
    // If the radius is invalid or extremely large (straight line), curvature is zero.
    if (R_squared <= 0)
    {
        _error[0] = 0.0;
        return;
    }
  
    const double R = std::sqrt(R_squared);
    // If the radius is very large, treat the path as a straight line (zero curvature).
    if (R > 1e6)
    {
        _error[0] = 0.0;
        return;
    }
    // STEP 3: Calculate curvature and the corresponding steering angle.
    const double kappa = 1.0 / R;
    const double steering_angle = std::atan(wheelbase * kappa);
    
    // STEP 4: The error is the calculated steering angle.
    // _error[0] = steering_angle;
    _error[0] = penaltyBoundToInterval(steering_angle, -M_PI_2 / 6, M_PI_2 / 6, penalty_eps);
    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeSteeringAngleGoal::computeError() _error[0]=%f\n", _error[0]);
  }


  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif