#ifndef EDGE_SHORTEST_PATH_H_
#define EDGE_SHORTEST_PATH_H_

#include <float.h>

#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/vertex_pose.h"

#include <Eigen/Core>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{

/**
 * @class EdgeShortestPath
 * @brief Edge defining the cost function for minimizing the Euclidean distance between two consectuive poses.
 *
 * @see TebOptimalPlanner::AddEdgesShortestPath
 */
class EdgeShortestPath : public BaseTebBinaryEdge<1, double, VertexPose, VertexPose> {
public:
  /**
   * @brief Construct edge.
   */
  EdgeShortestPath() { this->setMeasurement(0.); }

  /**
   * @brief Actual cost function
   */
  void computeError() {
    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeShortestPath()");
    const VertexPose *pose1 = static_cast<const VertexPose*>(_vertices[0]);
    const VertexPose *pose2 = static_cast<const VertexPose*>(_vertices[1]);
    _error[0] = (pose2->position() - pose1->position()).norm();

    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeShortestPath::computeError() _error[0]=%f\n", _error[0]);
  }

public:
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif /* EDGE_SHORTEST_PATH_H_ */
