#ifndef EDGE_START_STEERING_ANGLE_H
#define EDGE_START_STEERING_ANGLE_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{
/**
 * @class EdgeStartSteeringAngle
 * @brief Edge that constrains the steering rate for the first two segments of the trajectory.
 *
 * This edge ensures that the transition from the current (measured) steering angle
 * to the planned steering angle of the first segment, AND the transition from the
 * first to the second planned steering angle are both feasible within the robot's
 * steering rate limits.
 *
 * It takes 5 vertices: p0, p1, p2, dt0, dt1.
 * It has a 2-dimensional error vector:
 *  - _error[0]: Required steering rate for the first segment (p0->p1)
 *  - _error[1]: Required steering rate for the second segment (p1->p2)
 */
class EdgeStartSteeringAngle : public BaseTebMultiEdge<2, double>
{
public:
  EdgeStartSteeringAngle()
  {
    this->resize(5); // p0, p1, p2, dt0, dt1
  }

  void computeError() override
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;
    const double steering_rate_max = params_->FollowPath.robot.steering_rate_max;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;

    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeStartSteeringAngle()");
    const auto* p0 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* p1 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* p2 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt0 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    // === Segment 1: p0 -> p1 ===
    double steering_angle_cmd1 = 0.0;
    if (dt0->dt() > 1e-6)
    {
        const Eigen::Vector2d diff1 = p1->position() - p0->position();
        const double angle_diff1 = angles::normalize_angle(p1->theta() - p0->theta());
        const double planned_omega1 = angle_diff1 / dt0->dt();
        const double planned_vx_sign1 = fast_sigmoid(100 * (diff1.x() * cos(p0->theta()) + diff1.y() * sin(p0->theta())));
        const double planned_vx1 = diff1.norm() / dt0->dt() * planned_vx_sign1;

        if (std::abs(planned_vx1) > 1e-5)
            steering_angle_cmd1 = std::atan2(planned_omega1 * wheelbase, planned_vx1);
        else if (std::abs(planned_omega1) > 1e-5)
            steering_angle_cmd1 = (planned_omega1 > 0) ? M_PI_2 : -M_PI_2;
    }
    
    // Check for 180-degree turn ambiguity
    if (std::abs(steering_angle_cmd1 - measured_steering_angle_) > M_PI_2)
        steering_angle_cmd1 -= std::copysign(M_PI, steering_angle_cmd1);


    const double delta_phi1 = angles::normalize_angle(steering_angle_cmd1 - measured_steering_angle_);
    const double required_steering_rate1 = (dt0->dt() > 1e-6) ? (delta_phi1 / dt0->dt()) : 0.0;
    _error[0] = penaltyBoundFromBelow(steering_rate_max, std::abs(required_steering_rate1), penalty_eps);

    // === Segment 2: p1 -> p2 ===
    double steering_angle_cmd2 = 0.0;
    if (dt1->dt() > 1e-6)
    {
        const Eigen::Vector2d diff2 = p2->position() - p1->position();
        const double angle_diff2 = angles::normalize_angle(p2->theta() - p1->theta());
        const double planned_omega2 = angle_diff2 / dt1->dt();
        const double planned_vx_sign2 = fast_sigmoid(100 * (diff2.x() * cos(p1->theta()) + diff2.y() * sin(p1->theta())));
        const double planned_vx2 = diff2.norm() / dt1->dt() * planned_vx_sign2;

        if (std::abs(planned_vx2) > 1e-5)
            steering_angle_cmd2 = std::atan2(planned_omega2 * wheelbase, planned_vx2);
        else if (std::abs(planned_omega2) > 1e-5)
            steering_angle_cmd2 = (planned_omega2 > 0) ? M_PI_2 : -M_PI_2;
    }

    // Check for 180-degree turn ambiguity (comparing to the previous command)
    if (std::abs(steering_angle_cmd2 - steering_angle_cmd1) > M_PI_2)
        steering_angle_cmd2 -= std::copysign(M_PI, steering_angle_cmd2);

    const double delta_phi2 = angles::normalize_angle(steering_angle_cmd2 - steering_angle_cmd1);
    const double required_steering_rate2 = (dt1->dt() > 1e-6) ? (delta_phi2 / dt1->dt()) : 0.0;
    _error[1] = penaltyBoundFromBelow(steering_rate_max, std::abs(required_steering_rate2), penalty_eps);
    _error[1] = 0.0;
  }

  void setInitialSteeringAngle(double angle)
  {
    measured_steering_angle_ = angle;
  }

protected:
  double measured_steering_angle_ = 0.0;
};

} // end namespace

#endif