#ifndef EDGE_ACCELERATION_HOLONOMIC_GOAL_H_
#define EDGE_ACCELERATION_HOLONOMIC_GOAL_H_

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

#include <geometry_msgs/msg/twist.hpp>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{
/**
 * @class EdgeAccelerationHolonomicGoal
 * @brief Edge defining the cost function for limiting the translational and rotational acceleration at the end of the trajectory.
 * 
 * The edge depends on three vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \Delta T_i \f$, an initial velocity defined by setGoalVelocity()
 * and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [ax, ay, omegadot ]^T ) \cdot weight \f$. \n
 * \e ax is calculated using the difference quotient (twice) and the x-position parts of the poses \n
 * \e ay is calculated using the difference quotient (twice) and the y-position parts of the poses \n
 * \e omegadot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi].  \n
 * \e weight can be set using setInformation() \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval() \n
 * The dimension of the error / cost vector is 3: the first component represents the translational acceleration,
 * the second one is the strafing velocity and the third one the rotational acceleration.
 * @see TebOptimalPlanner::AddEdgesAcceleration
 * @see EdgeAccelerationHolonomic
 * @see EdgeAccelerationHolonomicStart
 * @remarks Do not forget to call setTebConfig()
 * @remarks Refer to EdgeAccelerationHolonomicStart() for defining boundary (initial) values at the end of the trajectory
 */  
class EdgeAccelerationHolonomicGoal : public BaseTebMultiEdge<3, const geometry_msgs::msg::Twist*>
{
public:
  /**
   * @brief Construct edge.
   */  
  EdgeAccelerationHolonomicGoal()
  {
    _measurement = nullptr;
    this->resize(3);
  }
  /**
   * @brief Actual cost function
   */ 
  void computeError() override
  {
    // read params
    const double a_max_x = params_->FollowPath.robot.a_max_x;
    const double a_max_y = params_->FollowPath.robot.a_max_y;
    const double a_max_theta = params_->FollowPath.robot.a_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;

    // TEB_ASSERT_MSG(cfg_ && _measurement, "You must call setTebConfig() and setGoalVelocity() on EdgeAccelerationGoal()");
    const auto* pose_pre_goal = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose_goal = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* dt = dynamic_cast<const VertexTimeDiff*>(_vertices[2]);

    // VELOCITY & ACCELERATION

    Eigen::Vector2d diff = pose_goal->position() - pose_pre_goal->position();    
    
    double cos_theta1 = std::cos(pose_pre_goal->theta());
    double sin_theta1 = std::sin(pose_pre_goal->theta()); 
    
    // transform pose2 into robot frame pose1 (inverse 2d rotation matrix)
    double p1_dx =  cos_theta1*diff.x() + sin_theta1*diff.y();
    double p1_dy = -sin_theta1*diff.x() + cos_theta1*diff.y();
   
    double vel1_x = p1_dx / dt->dt();
    double vel1_y = p1_dy / dt->dt();
    double vel2_x = _measurement->linear.x;
    double vel2_y = _measurement->linear.y;
    
    double acc_lin_x  = (vel2_x - vel1_x) / dt->dt();
    double acc_lin_y  = (vel2_y - vel1_y) / dt->dt();

    _error[0] = penaltyBoundToInterval(acc_lin_x, a_max_x, penalty_eps);
    _error[1] = penaltyBoundToInterval(acc_lin_y, a_max_y, penalty_eps);
    
    // ANGULAR ACCELERATION
    double omega1 = angles::normalize_angle(pose_goal->theta() - pose_pre_goal->theta()) / dt->dt();
    double omega2 = _measurement->angular.z;
    double acc_rot  = (omega2 - omega1) / dt->dt();
      
    _error[2] = penaltyBoundToInterval(acc_rot, a_max_theta, penalty_eps);

    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeAccelerationGoal::computeError() translational: _error[0]=%f\n",_error[0]);
    // TEB_ASSERT_MSG(std::isfinite(_error[1]), "EdgeAccelerationGoal::computeError() strafing: _error[1]=%f\n",_error[1]);
    // TEB_ASSERT_MSG(std::isfinite(_error[2]), "EdgeAccelerationGoal::computeError() rotational: _error[2]=%f\n",_error[2]);
  }
  
  /**
   * @brief Set the goal / final velocity that is taken into account for calculating the acceleration
   * @param vel_goal twist message containing the translational and rotational velocity
   */    
  void setGoalVelocity(const geometry_msgs::msg::Twist& vel_goal)
  {
    _measurement = &vel_goal;
  }

  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
}; 

}; // end namespace

#endif /* EDGE_ACCELERATION_HOLONOMIC_GOAL_H_ */