#ifndef EDGE_TIMEOPTIMAL_H_
#define EDGE_TIMEOPTIMAL_H_

#include <float.h>

#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"

#include <Eigen/Core>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{

  
/**
 * @class EdgeTimeOptimal
 * @brief Edge defining the cost function for minimizing transition time of the trajectory.
 * 
 * The edge depends on a single vertex \f$ \Delta T_i \f$ and minimizes: \n
 * \f$ \min \Delta T_i^2 \cdot scale \cdot weight \f$. \n
 * \e scale is determined using the penaltyEquality() function, since we experiences good convergence speeds with it. \n
 * \e weight can be set using setInformation() (something around 1.0 seems to be fine). \n
 * @see TebOptimalPlanner::AddEdgesTimeOptimal
 * @remarks Do not forget to call setTebConfig()
 */
class EdgeTimeOptimal : public BaseTebUnaryEdge<1, double, VertexTimeDiff>
{
public:
    
  /**
   * @brief Construct edge.
   */
  EdgeTimeOptimal()
  {
    this->setMeasurement(0.);
  }
  
  /**
   * @brief Actual cost function
   */
  void computeError() override
  {
    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeTimeOptimal()");
    const auto* timediff = dynamic_cast<const VertexTimeDiff*>(_vertices[0]);

   _error[0] = timediff->dt();
  
    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeTimeOptimal::computeError() _error[0]=%f\n",_error[0]);
  }

#ifdef USE_ANALYTIC_JACOBI
  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   */
  void linearizeOplus()
  {
    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeTimeOptimal()");
    _jacobianOplusXi( 0 , 0 ) = 1;
  }
#endif
  
  
       
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

}; // end namespace

#endif /* EDGE_TIMEOPTIMAL_H_ */
