#ifndef EDGE_JERK_H
#define EDGE_JERK_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
/**
 * @class EdgeJerk
 * @brief Edge defining the cost function for limiting the translational and rotational jerk.
 *
 * This edge implements a G3-continuity constraint.
 * It depends on four consecutive vertices s_i, s_i+1, s_i+2, s_i+3 and three time diffs.
 * It minimizes: penalty( [jerk_lin, jerk_rot]^T )
 * Jerk is calculated as the difference quotient of the accelerations.
 * The error dimension is 2 (linear and rotational jerk).
 */
class EdgeJerk : public BaseTebMultiEdge<2, double>
{
public:
  EdgeJerk()
  {
    this->resize(7); // 4 Poses, 3 TimeDiffs
  }

  void computeError()
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    
    const VertexPose* pose1 = static_cast<const VertexPose*>(_vertices[0]);
    const VertexPose* pose2 = static_cast<const VertexPose*>(_vertices[1]);
    const VertexPose* pose3 = static_cast<const VertexPose*>(_vertices[2]);
    const VertexPose* pose4 = static_cast<const VertexPose*>(_vertices[3]);

    const VertexTimeDiff* dt1 = static_cast<const VertexTimeDiff*>(_vertices[4]);
    const VertexTimeDiff* dt2 = static_cast<const VertexTimeDiff*>(_vertices[5]);
    const VertexTimeDiff* dt3 = static_cast<const VertexTimeDiff*>(_vertices[6]);

    // ==================== LINEAR PART ====================
    const Eigen::Vector2d diff1 = pose2->position() - pose1->position();
    const Eigen::Vector2d diff2 = pose3->position() - pose2->position();
    const Eigen::Vector2d diff3 = pose4->position() - pose3->position();

    double vel1 = diff1.norm() / dt1->dt();
    double vel2 = diff2.norm() / dt2->dt();
    double vel3 = diff3.norm() / dt3->dt();

    vel1 *= fast_sigmoid(100 * (diff1.x() * cos(pose1->theta()) + diff1.y() * sin(pose1->theta())));
    vel2 *= fast_sigmoid(100 * (diff2.x() * cos(pose2->theta()) + diff2.y() * sin(pose2->theta())));
    vel3 *= fast_sigmoid(100 * (diff3.x() * cos(pose3->theta()) + diff3.y() * sin(pose3->theta())));

    const double acc_lin1 = (vel2 - vel1) * 2 / (dt1->dt() + dt2->dt());
    const double acc_lin2 = (vel3 - vel2) * 2 / (dt2->dt() + dt3->dt());

    const double jerk_lin = (acc_lin2 - acc_lin1) * 2 / (dt1->dt() + dt2->dt() + dt3->dt());
    _error[0] = penaltyBoundToInterval(jerk_lin, jerk_max_x, penalty_eps);

    // ==================== ROTATIONAL PART ====================
    const double angle_diff1 = angles::normalize_angle(pose2->theta() - pose1->theta());
    const double angle_diff2 = angles::normalize_angle(pose3->theta() - pose2->theta());
    const double angle_diff3 = angles::normalize_angle(pose4->theta() - pose3->theta());

    const double omega1 = angle_diff1 / dt1->dt();
    const double omega2 = angle_diff2 / dt2->dt();
    const double omega3 = angle_diff3 / dt3->dt();

    const double acc_rot1 = (omega2 - omega1) * 2 / (dt1->dt() + dt2->dt());
    const double acc_rot2 = (omega3 - omega2) * 2 / (dt2->dt() + dt3->dt());

    const double jerk_rot = (acc_rot2 - acc_rot1) * 2 / (dt1->dt() + dt2->dt() + dt3->dt());
    _error[1] = penaltyBoundToInterval(jerk_rot, jerk_max_theta, penalty_eps);
  }
};

} // end namespace

#endif