#ifndef EDGE_PATH_SMOOTHNESS_H
#define EDGE_PATH_SMOOTHNESS_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"

#include <angles/angles.h>
#include <rclcpp/logging.hpp>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{
/**
 * @class EdgePathSmoothness
 * @brief A purely geometric edge for path smoothness.
 *
 * This edge penalizes sharp corners by minimizing the angle between consecutive path segments.
 * It is independent of time and velocity, forcing the geometry of the path itself to be smooth.
 * It connects three consecutive vertices s_i, s_i+1, s_i+2.
 * The error is the angle between the vector (s_i+1 - s_i) and (s_i+2 - s_i+1).
 */
class EdgePathSmoothness : public BaseTebBinaryEdge<1 ,double, VertexPose, VertexPose>
{
public:
  /**
   * @brief Construct edge.
   */
  EdgePathSmoothness()
  {
    this->setMeasurement(0.);
  }

  /**
   * @brief Actual cost function
   */
  void computeError() override {
    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgePathSmoothness()");
    const auto *pose1 = dynamic_cast<const VertexPose *>(_vertices[0]);
    const auto *pose2 = dynamic_cast<const VertexPose *>(_vertices[1]);

    // Calculate change value of angle
    // _error[0] = pow(pose2->theta() - pose1->theta(), 2);
    _error[0] = std::abs(angles::normalize_angle(pose1->theta() - pose2->theta()));

    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgePathSmoothness::computeError() _error[0]=%f\n", _error[0]);
  }


  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif