#ifndef EDGE_GOAL_ANGULAR_VELOCITY_ZERO_H
#define EDGE_GOAL_ANGULAR_VELOCITY_ZERO_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{
/**
 * @class EdgeGoalAngularVelocityZero
 * @brief Edge defining a cost function to force the angular velocity at the goal to be zero.
 *
 * This edge directly penalizes the angular velocity in the last trajectory segment.
 * It is a more direct kinematic constraint than using path curvature.
 * The edge depends on the last two poses (s_n-1, s_n) and the last time diff (dt_n-1).
 * It minimizes: penalty( omega_goal )
 * The error dimension is 1.
 */
class EdgeGoalAngularVelocityZero : public BaseTebMultiEdge<1, double>
{
public:
  EdgeGoalAngularVelocityZero()
  {
    // 9 vertices: 5 poses and 4 time diffs
    this->resize(9);
  }

  void computeError() override
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;

    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeGoalAngularVelocityZero()");
    // Get all 9 vertices
    const auto* pose_n_minus_4 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose_n_minus_3 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose_n_minus_2 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* pose_n_minus_1 = dynamic_cast<const VertexPose*>(_vertices[3]);
    const auto* pose_n = dynamic_cast<const VertexPose*>(_vertices[4]);
    
    const auto* dt_n_minus_4 = dynamic_cast<const VertexTimeDiff*>(_vertices[5]);
    const auto* dt_n_minus_3 = dynamic_cast<const VertexTimeDiff*>(_vertices[6]);
    const auto* dt_n_minus_2 = dynamic_cast<const VertexTimeDiff*>(_vertices[7]);
    const auto* dt_n_minus_1 = dynamic_cast<const VertexTimeDiff*>(_vertices[8]);

    // === STEP 1: Calculate angular velocity 'omega' using linear regression (robust) ===
    std::vector<double> t(5);
    std::vector<double> theta(5);
    t[0] = 0;
    theta[0] = pose_n_minus_4->theta();
    t[1] = dt_n_minus_4->dt();
    theta[1] = theta[0] + angles::normalize_angle(pose_n_minus_3->theta() + theta[0]);
    t[2] = t[1] + dt_n_minus_3->dt();
    theta[2] = theta[1] + angles::normalize_angle(pose_n_minus_2->theta() + theta[1]);
    t[3] = t[2] + dt_n_minus_2->dt();
    theta[3] = theta[2] + angles::normalize_angle(pose_n_minus_1->theta() + theta[2]);
    t[4] = t[3] + dt_n_minus_1->dt();
    theta[4] = theta[3] + angles::normalize_angle(pose_n->theta() + theta[3]);

    Eigen::Matrix<double, 5, 2> A_rot;
    Eigen::Matrix<double, 5, 1> B_rot;
    for (int i = 0; i < 5; ++i) { A_rot(i, 0) = 1.0; A_rot(i, 1) = t[i]; B_rot(i, 0) = theta[i]; }
    const double omega = A_rot.colPivHouseholderQr().solve(B_rot)[1];

    // === STEP 2: Calculate linear velocity 'v' (robust) ===
    // We calculate the total distance traveled over the total time of the 5-pose window.
    const double dist1 = (pose_n_minus_3->position() - pose_n_minus_4->position()).norm();
    const double dist2 = (pose_n_minus_2->position() - pose_n_minus_3->position()).norm();
    const double dist3 = (pose_n_minus_1->position() - pose_n_minus_2->position()).norm();
    const double dist4 = (pose_n->position() - pose_n_minus_1->position()).norm();
    const double total_dist = dist1 + dist2 + dist3 + dist4;
    const double total_time = t[4]; // t[4] already holds the sum of all dt's

    // Handle the singularity case: if the robot is not moving, the steering angle is conceptually zero.
    if (total_time < 1e-6)
    {
        _error[0] = 0.0;
        return;
    }
    const double v = total_dist / total_time;

    // === STEP 3: Calculate the steering angle 'phi' ===
    // Handle the singularity case for velocity: if v is very close to zero, the steering angle is undefined
    // but can be treated as zero, as no turning motion is produced.
    if (std::abs(v) < 1e-4)
    {
        _error[0] = 0.0;
        return;
    }

    // Use atan2 for numerical stability. atan2(y, x) -> atan2(omega * L, v)
    const double steering_angle = std::atan2(omega * wheelbase, v);

    // === STEP 4: The error is the actual steering angle. ===
    _error[0] = steering_angle;

    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeGoalAngularVelocityZero::computeError() _error[0]=%f\n", _error[0]);
  }


  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif