#ifndef EDGE_G3_CONTINUITY_H
#define EDGE_G3_CONTINUITY_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
/**
 * @class EdgeG3Continuity
 * @brief Edge for penalizing the curvature rate to approximate G3 continuity.
 *
 * This edge minimizes the change in curvature over three consecutive poses.
 * It is specifically designed to handle 360-degree steering capabilities by
 * calculating the error in the steering angle space and normalizing the difference.
 * This version correctly handles the relationship between curvature and steering
 * angle for both forward and backward motion.
 *
 * The underlying cost function is:
 *   ( normalize_angle(phi_2 - phi_1) )^2
 * where phi_1 and phi_2 are the steering angles corresponding to the
 * curvatures of the two segments, correctly calculated for the driving direction.
 *
 * @see VertexPose
 */
class EdgeG3Continuity : public BaseTebMultiEdge<1, std::nullptr_t>
{
public:
  /**
   * @brief Construct edge.
   */
  EdgeG3Continuity()
  {
    this->resize(3);
  }

  /**
   * @brief Actual cost function
   */
  void computeError()
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;
    // const double steering_rate_max = params_->FollowPath.robot.steering_rate_max;
    // const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;

    const VertexPose* pose_prev = static_cast<const VertexPose*>(_vertices[0]);
    const VertexPose* pose_curr = static_cast<const VertexPose*>(_vertices[1]);
    const VertexPose* pose_next = static_cast<const VertexPose*>(_vertices[2]);
    // const VertexTimeDiff* dt1 = static_cast<const VertexTimeDiff*>(_vertices[3]);
    // const VertexTimeDiff* dt2 = static_cast<const VertexTimeDiff*>(_vertices[4]);

    // Approximate path length between poses
    const Eigen::Vector2d diff1 = pose_curr->position() - pose_prev->position();
    const double dist1 = diff1.norm();
    const Eigen::Vector2d diff2 = pose_next->position() - pose_curr->position();
    const double dist2 = diff2.norm();

    // Check for small distances to avoid division by zero
    if (dist1 < 1e-4 || dist2 < 1e-4)
    {
      _error[0] = 0.0;
      return;
    }

    // --- Curvature Calculation ---
    const double delta_theta1 = angles::normalize_angle(pose_curr->theta() - pose_prev->theta());
    const double delta_theta2 = angles::normalize_angle(pose_next->theta() - pose_curr->theta());
    const double dir1 = diff1.x() * std::cos(pose_prev->theta()) + diff1.y() * std::sin(pose_prev->theta());
    const double dir2 = diff2.x() * std::cos(pose_curr->theta()) + diff2.y() * std::sin(pose_curr->theta());
    const double kappa1 = (dir1 >= 0) ? (delta_theta1 / dist1) : (-delta_theta1 / dist1);
    const double kappa2 = (dir2 >= 0) ? (delta_theta2 / dist2) : (-delta_theta2 / dist2);

    // 1. Konvertiere die Krümmung (kappa) in den Lenkwinkel (phi).
    //    BEACHTE: Bei Rückwärtsfahrt kehrt sich die Beziehung um!
    //    Forward:  phi = atan(kappa * L)
    //    Backward: phi = atan(-kappa * L)

    const double phi1 = (dir1 >= 0) ? atan(kappa1 * wheelbase) : atan(-kappa1 * wheelbase);
    const double phi2 = (dir2 >= 0) ? atan(kappa2 * wheelbase) : atan(-kappa2 * wheelbase);

    // 2. Berechne die normalisierte Differenz der Lenkwinkel.
    //    Dieser Schritt bleibt gleich und behandelt die 360°-Natur korrekt.
    const double phi2_ = unwrapSteeringAngle(phi2, phi1);
    // const double delta_phi = angles::normalize_angle(phi2 - phi1);
    const double delta_phi  = phi2_ - phi1;  // kein normalize_angle nach unwrap!

    // // --- Unwrap phi2 relativ zu phi1 (konsistente Vorzeichen wie in EdgeSteeringRate)
    // const double phi2 = unwrapSteeringAngle(phi2_raw, phi1_raw);
    // const double phi1 = phi1_raw;

    // // --- Steuerrate: delta_phi / mittlere Zeit der beiden Segmente
    // const double avg_dt     = 0.5 * (dt1->dt() + dt2->dt());
    // const double delta_phi  = phi2 - phi1;  // kein normalize_angle nach unwrap!
    // const double steer_rate = (avg_dt > 1e-6) ? (std::abs(delta_phi) / avg_dt) : 0.0;

    // 3. Der Fehler ist diese normalisierte Winkeldifferenz.
    _error[0] = delta_phi;
    // _error[0] = penaltyBoundFromBelow(delta_dot_max, steer_rate, penalty_eps);
  }

public:
  /// Pick the equivalent angle (φ or φ±π) closest to reference
  double unwrapSteeringAngle(double phi, double reference)
  {
    const double d0 = std::abs(angles::normalize_angle(phi - reference));
    const double d1 = std::abs(angles::normalize_angle(phi + M_PI - reference));
    const double d2 = std::abs(angles::normalize_angle(phi - M_PI - reference));
    if (d1 < d0 && d1 < d2) return phi + M_PI;
    if (d2 < d0 && d2 < d1) return phi - M_PI;
    return phi;
  }
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif