#pragma once

#include <Eigen/Core>
#include <costmap_converter_msgs/msg/obstacle_array_msg.hpp>
#include <memory>
#include <nav2_teb_controller/obstacles/esdf.hpp>

#include "ackermann_msgs/msg/ackermann_drive.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "nav2_costmap_2d/costmap_2d_ros.hpp"
#include "nav2_teb_controller/core/footprint.hpp"
#include "nav2_teb_controller/core/teb_utils.hpp"
#include "nav2_teb_controller/core/timed_elastic_band.hpp"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/planner/planner_interface.hpp"
#include "nav_msgs/msg/path.hpp"

// g2o custom edges and vertices for the TEB planner
#include <nav2_teb_controller/g2o_types/edge_path_smoothness.h>
#include <nav2_teb_controller/g2o_types/edge_shortest_path.h>
#include <nav2_teb_controller/g2o_types/edge_time_optimal.h>
// #include <nav2_teb_controller/g2o_types/edge_via_point.h>
#include <nav2_teb_controller/g2o_types/edge_acceleration.h>
#include <nav2_teb_controller/g2o_types/edge_acceleration_goal.h>
#include <nav2_teb_controller/g2o_types/edge_acceleration_holonomic.h>
#include <nav2_teb_controller/g2o_types/edge_acceleration_holonomic_goal.h>
#include <nav2_teb_controller/g2o_types/edge_acceleration_holonomic_start.h>
#include <nav2_teb_controller/g2o_types/edge_acceleration_start.h>
#include <nav2_teb_controller/g2o_types/edge_costmap_obstacle.h>
#include <nav2_teb_controller/g2o_types/edge_esdf_obstacle.h>
#include <nav2_teb_controller/g2o_types/edge_g3_continuity.h>
#include <nav2_teb_controller/g2o_types/edge_goal_angular_velocity_zero.h>
#include <nav2_teb_controller/g2o_types/edge_jerk_new.h>
#include <nav2_teb_controller/g2o_types/edge_kinematic_car_like.h>
#include <nav2_teb_controller/g2o_types/edge_kinematics_diff.h>
#include <nav2_teb_controller/g2o_types/edge_snap.h>
#include <nav2_teb_controller/g2o_types/edge_start_steering_angle.h>
#include <nav2_teb_controller/g2o_types/edge_steering_angle_goal.h>
#include <nav2_teb_controller/g2o_types/edge_steering_rate.h>
#include <nav2_teb_controller/g2o_types/edge_steering_rate_goal.h>
#include <nav2_teb_controller/g2o_types/edge_steering_rate_start.h>
#include <nav2_teb_controller/g2o_types/edge_velocity.h>
#include <nav2_teb_controller/g2o_types/edge_velocity_holonomic.h>
// #include <nav2_teb_controller/g2o_types/edge_prefer_rotdir.h>

#include <g2o/core/block_solver.h>
#include <g2o/core/optimization_algorithm_gauss_newton.h>
#include <g2o/core/optimization_algorithm_levenberg.h>
#include <g2o/core/sparse_optimizer.h>
#include <g2o/core/robust_kernel_impl.h>

#include "g2o/solvers/cholmod/linear_solver_cholmod.h"
#include "g2o/solvers/csparse/linear_solver_csparse.h"
#include "g2o/solvers/dense/linear_solver_dense.h"
#include "g2o/solvers/eigen/linear_solver_eigen.h"

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller {

struct EdgeDescriptor {
  int num_poses;      // Anzahl Pose-Vertices
  int num_timediffs;  // Anzahl TimeDiff-Vertices
  int stride;         // wie viele Iterationen: n - stride
  int offset;         // Startindex: 0=vorne, -1=hinten (n - num_poses - |offset|)
  int info_dim;       // 1 oder 2 (Dimension der Information-Matrix)
};

class DiscreteTEBPlanner : public PlannerInterface<TimedElasticBand> {
public:
  explicit DiscreteTEBPlanner(const teb_controller::Params &params, const Footprint &footprint,
                              nav2_costmap_2d::Costmap2DROS *costmap_ros);

  bool plan(const nav_msgs::msg::Path &initial_plan,
            const geometry_msgs::msg::Twist &start_vel) override;

  bool hasDiverged() override;

  void clear() override;

  [[nodiscard]] const TimedElasticBand &getTEB() const override { return teb_; }

  void setFeedback(const ackermann_msgs::msg::AckermannDrive &feedback) override {
    ackermann_feedback_ = feedback;
  }

  void updateObstacleContainer(
      costmap_converter_msgs::msg::ObstacleArrayMsg::ConstSharedPtr obstacle_array = nullptr) override;

  void setObstacleMap(const ObstacleMap2D *esdf) override { esdf_ = esdf; }

  void setFixedGoal(bool fix) override { final_goal_ = fix; }

  bool optimizeTEB(int no_inner_iterations, int no_outer_iterations, bool compute_cost_afterwards);
  bool isOptimized() const { return optimized_; }

  void computeCurrentCost();

protected:
  std::shared_ptr<g2o::SparseOptimizer> initOptimizer();
  bool buildGraph();
  bool optimizeGraph(int no_inner_iterations, bool clear_after);
  void clearGraph();
  void writeBackOptimizedValues();
  void extractObstacles();

  // Vertices
  void AddTEBVertices();
  // Edges
  void AddEdgesVelocity();
  void AddEdgesAcceleration();
  void AddEdgesTimeOptimal();
  void AddEdgesShortestPath();
  void AddEdgesPathSmoothness();
  void AddEdgesJerk();
  void AddEdgesSnap();
  void AddEdgesSteeringAngleGoal();
  void AddEdgesSteeringRate();
  void AddEdgesGoalAngularVelocityZero();
  void AddEdgesStartSteeringAngle();
  void AddEdgesG3Continuity();
  void AddEdgesViaPoints();
  void AddEdgesKinematicsDiffDrive();
  void AddEdgesKinematicsCarlike();
  void AddEdgesObstacles();
  void addEdgesESDFObstacles();
  void AddEdgesPreferRotDir();

  // Add edges generic
  template <typename EdgeType, int InfoDim, typename... Args>
  void addEdgesGeneric(const EdgeDescriptor &desc, const std::array<double, InfoDim> &weights,
                       Args &&...args);

  // remove later in extra class
  [[nodiscard]] geometry_msgs::msg::Twist extractVelocity() const;
  [[nodiscard]] geometry_msgs::msg::Twist getVelocityCommand() const;

  // Velocity
  void setVelocityStart(const geometry_msgs::msg::Twist &vel_start) {
    vel_start_.first = true;
    vel_start_.second = vel_start;
  }
  void setVelocityGoal(const geometry_msgs::msg::Twist &vel_goal) {
    vel_goal_.first = true;
    vel_goal_.second = vel_goal;
  }
  void setGoal(const geometry_msgs::msg::Pose &goal) { goal_ = goal; }

  // implement later for collision checks
  static bool isTrajectoryFeasible() { return true; }
  static bool isPoseValid() { return true; }

  TimedElasticBand teb_;
  const teb_controller::Params &params_;
  const Footprint &footprint_;
  std::shared_ptr<g2o::SparseOptimizer> optimizer_;
  nav2_costmap_2d::Costmap2DROS *costmap_ros_ = nullptr;

  std::vector<Obstacle> obstacles_;
  const ObstacleMap2D *esdf_{nullptr};

  std::vector<VertexPose *> pose_vertices_;
  std::vector<VertexTimeDiff *> timediff_vertices_;

  std::pair<bool, geometry_msgs::msg::Twist>
      vel_start_;  //!< Store the initial velocity at the start pose
  std::pair<bool, geometry_msgs::msg::Twist>
      vel_goal_;  //!< Store the final velocity at the goal pose
  ackermann_msgs::msg::AckermannDrive ackermann_feedback_;
  geometry_msgs::msg::Pose goal_;
  bool final_goal_{};

  bool initialized_ = false;
  bool optimized_ = false;
  double cost_ = 0.0;
  double weight_multiplier_ = 0.0;

  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

}  // namespace nav2_teb_controller
