name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container:
      image: ros:jazzy

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src/nav2_teb_controller

      - name: Checkout costmap_converter
        uses: actions/checkout@v4
        with:
          repository: rst-tu-dortmund/costmap_converter
          ref: ros2
          path: ros2_ws/src/costmap_converter

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y clang-tidy clang-format
          rosdep update
          rosdep install --from-paths ros2_ws/src --ignore-src -r -y


      - name: Build costmap_converter
        run: |
          . /opt/ros/jazzy/setup.sh
          cd ros2_ws
          colcon build --packages-select costmap_converter_msgs costmap_converter

      - name: Build nav2_teb_controller
        run: |
          . /opt/ros/jazzy/setup.sh
          . ros2_ws/install/setup.sh
          cd ros2_ws
          colcon build --packages-select nav2_teb_controller

      - name: Run Tests
        run: |
          . /opt/ros/jazzy/setup.sh
          cd ros2_ws
          colcon test --packages-select nav2_teb_controller
          colcon test-result --verbose

      - name: Format Check
        run: |
          cd ros2_ws/src/nav2_teb_controller
          make format

      # - name: Lint
      #   run: |
      #     . /opt/ros/jazzy/setup.sh
      #     . ros2_ws/install/setup.sh
      #     cd ros2_ws/src/nav2_teb_controller
      #     make lint WS=$(pwd)/../../..

